import {DisplayCfg} from "./DisplayConfig.js";

export const TEXT_COLOR = "rgba(255,255,255,1)";
export const TEXT_WRONG_COLOR = "rgba(255,10,10,1)";
export const TEXT_HOLD_COLOR = "rgba(10,255,10,1)";
export const TEXT_SHADOW_COLOR = "rgba(255,0,255,1)";
export const OVERLAY_MAIN_TEXT_COLOR = "rgba(255,255,255,0.95)";
export const OVERLAY_SUB_TEXT_COLOR = "rgba(255,255,255,0.85)";
export const OVERLAY_TEXT_SHADOW_COLOR = "rgba(0,0,0,0.7)";
export const OVERLAY_BG_COLOR = "rgba(0,0,0,1)";

export const UIElements = [
    {
        key: "title",
        prefab: "Text",
        name: "UI_Title",
        layer: 0,
        x: DisplayCfg.size.w - 25,
        y: 20,
        text: "20 Seconds Game Jam",
        style: {
            font: "1000 50px MainMenuFont, sans-serif",
            fillStyle: TEXT_COLOR,
            textAlign: "right",
            textBaseline: "top",
            shadowColor: TEXT_SHADOW_COLOR,
            shadowBlur: 10,
        },
    },

    {
        key: "levelName",
        prefab: "Text",
        name: "UI_LevelName",
        layer: 0,
        x: DisplayCfg.size.w - 25,
        y: 80,
        text: "",
        style: {
            font: "400 30px MainMenuFont, sans-serif",
            fillStyle: TEXT_COLOR,
            textAlign: "right",
            textBaseline: "top",
            shadowColor: TEXT_SHADOW_COLOR,
            shadowBlur: 10,
        },
    },

    {
        key: "bpm",
        prefab: "Text",
        name: "UI_BPM",
        layer: 0,
        x: DisplayCfg.size.w - 25,
        y: 120,
        text: "",
        style: {
            font: "300 30px MainMenuFont, sans-serif",
            fillStyle: TEXT_COLOR,
            textAlign: "right",
            textBaseline: "top",
            shadowColor: TEXT_SHADOW_COLOR,
            shadowBlur: 10,
        },
    },

    {
        key: "hits",
        prefab: "Text",
        name: "UI_Hits",
        layer: 0,
        x: 24,
        y: 20,
        text: "",
        style: {
            font: "1000 60px MainMenuFont, sans-serif",
            fillStyle: TEXT_COLOR,
            textAlign: "left",
            textBaseline: "top",
            shadowColor: TEXT_SHADOW_COLOR,
            shadowBlur: 10,
        },
    },

    {
        key: "score",
        prefab: "Text",
        name: "UI_Score",
        layer: 0,
        x: 24,
        y: 100,
        text: "",
        style: {
            font: "1000 60px MainMenuFont, sans-serif",
            fillStyle: TEXT_COLOR,
            textAlign: "left",
            textBaseline: "top",
            shadowColor: TEXT_SHADOW_COLOR,
            shadowBlur: 10,
        },
    },

    {
        key: "hint",
        prefab: "Text",
        name: "UI_Hint",
        layer: 0,
        x: DisplayCfg.size.w / 2,
        y: DisplayCfg.size.h / 2,
        text: "",
        style: {
            font: "500 120px WowMenuFont, sans-serif",
            fillStyle: TEXT_COLOR,
            textAlign: "center",
            textBaseline: "top",
            shadowColor: TEXT_SHADOW_COLOR,
            shadowBlur: 10,
        },
    },

    {
        key: "result",
        prefab: "Text",
        name: "UI_Result",
        layer: 0,
        x: DisplayCfg.size.w / 2,
        y: DisplayCfg.size.h / 2 - 200,
        text: "",
        style: {
            font: "500 120px WowMenuFont, sans-serif",
            fillStyle: TEXT_COLOR,
            textAlign: "center",
            textBaseline: "top",
            shadowColor: TEXT_SHADOW_COLOR,
            shadowBlur: 10,
        },
    },

    {
        key: "combo",
        prefab: "Text",
        name: "UI_ComboPopup",
        layer: 1,
        x: 300,
        y: DisplayCfg.size.h / 2,
        text: "",
        style: {
            font: "400 200px WowMenuFont, sans-serif",
            fillStyle: TEXT_COLOR,
            textAlign: "center",
            textBaseline: "middle",
            shadowColor: TEXT_SHADOW_COLOR,
            shadowBlur: 50,
        },
        animation: {
            type: "comboPopup",
            duration: 0.6,
            autoHide: true,
        },
    },

    {
        key: "wrong",
        prefab: "Text",
        name: "UI_ComboPopup",
        layer: 1,
        x: DisplayCfg.size.w / 2 + 160,
        y: 200,
        text: "WRONG",
        style: {
            font: "400 200px WowMenuFont, sans-serif",
            fillStyle: TEXT_COLOR,
            textAlign: "center",
            textBaseline: "middle",
            shadowColor: TEXT_WRONG_COLOR,
            shadowBlur: 50,
        },
        animation: {
            type: "wrongPopup",
            duration: 0.8,
            autoHide: true,
        },
    },

    {
        key: "hold",
        prefab: "Text",
        name: "UI_ComboPopup",
        layer: 1,
        x: DisplayCfg.size.w / 2 + 240,
        y: 250,
        text: "HOLD",
        style: {
            font: "400 200px WowMenuFont, sans-serif",
            fillStyle: TEXT_COLOR,
            textAlign: "center",
            textBaseline: "middle",
            shadowColor: TEXT_HOLD_COLOR,
            shadowBlur: 50,
        },
        animation: {
            type: "holdPopup",
            duration: 0.8,
            autoHide: true,
        },
    },

    {
        key: "overlayMain",
        prefab: "Text",
        name: "UI_OverlayMainText",
        layer: 1000,
        x: DisplayCfg.size.w / 2,
        y: DisplayCfg.size.h / 2 - 40,
        text: "",
        style: {
            font: "600 90px MainMenuFont, sans-serif",
            fillStyle: OVERLAY_MAIN_TEXT_COLOR,
            textAlign: "center",
            textBaseline: "middle",
            shadowColor: OVERLAY_TEXT_SHADOW_COLOR,
            shadowBlur: 10,
            shadowOffsetX: 0,
            shadowOffsetY: 4,
        },
    },

    {
        key: "overlaySub",
        prefab: "Text",
        name: "UI_OverlaySubText",
        layer: 1001,
        x: DisplayCfg.size.w / 2,
        y: DisplayCfg.size.h / 2 + 40,
        text: "",
        style: {
            font: "400 60px MainMenuFont, sans-serif",
            fillStyle: OVERLAY_SUB_TEXT_COLOR,
            textAlign: "center",
            textBaseline: "middle",
            shadowColor: OVERLAY_TEXT_SHADOW_COLOR,
            shadowBlur: 8,
            shadowOffsetX: 0,
            shadowOffsetY: 3,
        },
    },

    {
        key: "gameName",
        prefab: "Text",
        name: "UI_GameName",
        layer: 1002,
        x: DisplayCfg.size.w / 2,
        y: 250,
        text: "Hungry Tree Friends",
        visible: false,
        style: {
            font: "1000 120px MainMenuFont, sans-serif",
            fillStyle: TEXT_COLOR,
            textAlign: "center",
            textBaseline: "top",
            shadowColor: OVERLAY_TEXT_SHADOW_COLOR,
            shadowBlur: 8,
            shadowOffsetX: 0,
            shadowOffsetY: 3,
        },
    },

    {
        key: "overlayBg",
        prefab: "Rect",
        name: "UI_OverlayBg",
        layer: 999,
        x: 0,
        y: 0,
        rect: {
            w: DisplayCfg.size.w,
            h: DisplayCfg.size.h,
            useOverlayAlpha: true,
        },
        style: {
            fillStyle: OVERLAY_BG_COLOR,
        },
        visible: true,
    },
];

export const UIConstants = {
    OVERLAY_DARKEN_FACTOR: 0.75,
    OVERLAY_FULL_ALPHA: 1.0,
    OVERLAY_EPSILON: 0.01,
};

export const OverlayConstants = {
    FADE_SPEED: 2.0,
};

export const Texts = {
    title: "20 Seconds Game Jam",
    levelName: (id, name) => `Level ${id}: ${name}`,
    bpm: bpm => `${bpm} BPM`,
    hits: (hits, total) => `Hits: ${hits} / ${total}`,
    score: score => `Score: x${score}`,
    combo: combo => `X${combo}`,
    wrong: `WRONG`,
    hold: `HOLD`,
    hintStart: "Press click/tap to start",
    hintContinue: "Press click/tap to continue",
    hintRetry: "Press click/tap to retry",
    hintRestart: "Press click/tap to restart",
    accuracyResult: percent => `Accuracy: ${percent}%`,
};

export const UIPhaseVisibility = {
    intro: {
        gameName: true,
        hint: true,
        title: false,
        levelName: false,
        bpm: false,
        hits: false,
        score: false,
        result: false,
        combo: false,
        overlayBg: true,
        overlayMain: true,
        overlaySub: true,
    },
    playing: {
        gameName: false,
        hint: false,
        title: true,
        levelName: true,
        bpm: true,
        hits: true,
        score: true,
        result: true,
        combo: true,
        overlayBg: false,
        overlayMain: false,
        overlaySub: false,
    },
    between: {
        gameName: false,
        hint: false,
        title: true,
        levelName: false,
        bpm: false,
        hits: true,
        score: true,
        result: true,
        combo: true,
        overlayBg: true,
        overlayMain: true,
        overlaySub: true,
    },
    restart: {
        gameName: false,
        hint: false,
        title: true,
        levelName: true,
        bpm: true,
        hits: true,
        score: true,
        result: true,
        combo: true,
        overlayBg: true,
        overlayMain: true,
        overlaySub: true,
    },
    fadeOutToPlay: {
        gameName: false,
        hint: true,
        title: false,
        levelName: false,
        bpm: false,
        hits: false,
        score: false,
        result: false,
        combo: false,
        overlayBg: false,
        overlayMain: false,
        overlaySub: false,
    },
};
